import Head from "next/head";
import { Inter } from "@next/font/google";
import { BsFillSunFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillFacebook,
} from "react-icons/ai";
import React, { use } from "react";
import { useState } from "react";
import Image from "next/image";
import omar from "../public/images/omar.png";
import sweUyghur from "../public/images/peojects/swe-uyghur.png";
import poster from "../public/images/peojects/poster.png";
import yummy from "../public/images/peojects/yummy.png";
import foodOrder from "../public/images/peojects/food-order-app.png";
import sinus from "../public/images/peojects/sinus.png";
import figma from "../public/images/peojects/design-principer.png";
import html from "../public/images/logos/html-img.png";
import css from "../public/images/logos/css-img.png";
import js from "../public/images/logos/js-img.png";
import vscode from "../public/images/logos/vscode-img.png";
import materialui from "../public/images/logos/materialui-img.png";
import vue from "../public/images/logos/vue-img.png";
import react from "../public/images/logos/react-img.png";
import expo from "../public/images/logos/expo-img.png";
import node from "../public/images/logos/node-img.png";
import npm from "../public/images/logos/npm-img.png";
import sqlite from "../public/images/logos/sqlite-img.png";
import mongodb from "../public/images/logos/mongodb-img.png";
import git from "../public/images/logos/git-img.png";
import github from "../public/images/logos/github.png";
import figmaa from "../public/images/logos/figma-img.png";
import access from "../public/images/logos/access-img.png";
import responsive from "../public/images/logos/responsive-img.png";
import trello from "../public/images/logos/trello.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Omarhuba</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-800 dark:bg-white min-h-screen ">
        <section>
          <nav className="p-8 flex justify-between ">
            <h1 className="text-3xl dark:text-gray-600 text-white">
              Portfolio
            </h1>
            <ul className="flex xl:p-0">
              <li className="px-5 text-xl font-bold text-cyan-500">
                <a href="#">Home</a>
              </li>
              <li className="px-5 text-xl font-bold text-cyan-500">
                <a href="#">About</a>
              </li>
              <li className="px-5 text-xl font-bold text-cyan-500">
                <a href="#">Projects</a>
              </li>
              <li className="px-5 text-xl font-bold text-cyan-500">
                <a href="#">Contact</a>
              </li>
              <li className="px-5 text-xl font-bold text-cyan-500">
                <BsFillSunFill
                  className="cursor-pointer text-2xl"
                  onClick={() => {
                    setDarkMode(!darkMode), console.log("click!");
                  }}
                />
              </li>
            </ul>
          </nav>
        </section>
        <div className="bg-cover bg-center bg-backgroundImage h-screen ">
          <h1 className="flex justify-end p-20 text-6xl text-white ">
            Omar.Mutalifu
          </h1>
          <h1 className="flex justify-end px-20 text-6xl text-white ">
            Javascript Developer
          </h1>
        </div>

        <section className="felx items-center felx-column text-center w-3/5 m-auto text-white">
          <h1 className="text-6xl text-gray-500 p-20 ">About Me</h1>
          <Image className="rounded-full w-80 m-auto" src={omar} alt="omar" />
          <h1 className="text-4xl text-cyan-400 p-10">
            Hi, I am Aimaierjiang Mutalifu
          </h1>
          <h3 className="text-2xl p-10 text-white dark:text-gray-600">
            I am a <span className="text-cyan-400">Developer</span>,{" "}
            <span className="text-cyan-400">Husband</span>, and{" "}
            <span className="text-cyan-400">Father</span> of Twins
          </h3>
          <p className="text-2xl p-10 text-white dark:text-gray-600">
            I am a lively, happy and ambitious student from the IT University
            and also the father of two twin boys. I came to Sweden in 2015 and
            live in southern Stockholm with my family. In 2021, I decided to
            change the bus driver profession to become a programmer - a dream I
            had for many years.
          </p>
        </section>
        <section className="p-10">
          <h1 className="text-6xl text-gray-500 p-20 text-center">Projects</h1>
          <div className="lg:grid grid-cols-2 gap-8">
            <div className="flex flex-col items-center text-center shadow-lg p-10 rounded-xl my-10  bg-gray-100 flex-1">
              <Image src={sweUyghur} width={300} height={200} alt="sweUyghur" />
              <h2 className="py-2 text-3xl">Swe-Uyghur(Fullstack)</h2>
              <p className="py-2">
                Swe-Uyghur Fotball Club är min fotball club och Jag bygger den
                för att vi ska skapa konto, lägga inlägg, sälja våran producter
                osv . Projekt byggdes av Node.js, Express.js, Mongoose, MVC,
                Filuppladdning, JWT, Bcrypt, RBAC, Fullt fungerande endpoints.
              </p>
              <button className="bg-gradient-to-r from-cyan-500 to-blue-500  px-4 py-2 my-3 border-none rounded-md ">
                VIEW CODE
              </button>
            </div>
            <div className="flex flex-col items-center text-center shadow-lg p-10 rounded-xl my-10  bg-gray-100 flex-1">
              <Image src={poster} width={600} height={200} alt="sweUyghur" />
              <Image src={poster} width={600} height={200} alt="sweUyghur" />
              <h2 className="py-2 text-3xl">Swe-Uyghur(Fullstack)</h2>
              <p className="py-2">
                Swe-Uyghur Fotball Club är min fotball club och Jag bygger den
                för att vi ska skapa konto, lägga inlägg, sälja våran producter
                osv . Projekt byggdes av Node.js, Express.js, Mongoose, MVC,
                Filuppladdning, JWT, Bcrypt, RBAC, Fullt fungerande endpoints.
              </p>
              <button className="bg-gradient-to-r from-cyan-500 to-blue-500  px-4 py-2 my-3 border-none rounded-md ">
                VIEW CODE
              </button>
            </div>
            <div className="flex flex-col items-center text-center shadow-lg p-10 rounded-xl my-10  bg-gray-100 flex-1">
              <Image src={yummy} width={600} height={200} alt="sweUyghur" />
              <Image src={yummy} width={600} height={200} alt="sweUyghur" />
              <Image src={yummy} width={600} height={200} alt="sweUyghur" />
              <h2 className="py-2 text-3xl">Coldn Yummy</h2>
              <p className="py-2">
                Cold n Yummy™ vill ha en kampanjsida för framröstning av en ny
                glassmak. Användare väljer en smak och skickar med sitt namn och
                e-mail-adress för att rösta på den. Man ska även kunna se
                topplistan på de mest populära smakerna.
              </p>
              <button className="bg-gradient-to-r from-cyan-500 to-blue-500  px-4 py-2 my-3 border-none rounded-md ">
                VIEW CODE
              </button>
            </div>
            <div className="flex flex-col items-center text-center shadow-lg p-10 rounded-xl my-10  bg-gray-100 flex-1">
              <Image src={foodOrder} width={600} height={200} alt="sweUyghur" />
              <h2 className="py-2 mt-16 text-3xl">Food-Order-React-APP</h2>
              <p className="py-2">
                Food-Order-App är en enkel beställnings app. Den byggdes av
                React, Man kan beställa food, add item, remove item osv
              </p>
              <button className="bg-gradient-to-r from-cyan-500 to-blue-500  px-4 py-2 my-3 border-none rounded-md ">
                VIEW CODE
              </button>
            </div>
            <div className="flex flex-col items-center text-center shadow-lg p-10 rounded-xl my-10  bg-gray-100 flex-1">
              <Image src={sinus} width={600} height={200} alt="sweUyghur" />
              <h2 className="py-2 mt-16 text-3xl">Sinus Web Shop(Vue)</h2>
              <p className="py-2">
                En e-handelsbutik byggd i Vue JS med VueX och routing. Kunder
                kan skapa ett konto för att spara sin information och det finns
                även ett admingränssnitt för att skapa, läsa, uppdatera och ta
                bort produkter och beställningar.
              </p>
              <button className="bg-gradient-to-r from-cyan-500 to-blue-500  px-4 py-2 my-3 border-none rounded-md ">
                VIEW CODE
              </button>
            </div>
            <div className="flex flex-col items-center text-center shadow-lg p-10 rounded-xl my-10  bg-gray-100 flex-1">
              <Image src={figma} width={600} height={200} alt="sweUyghur" />
              <h2 className="py-2 mt-16 text-3xl">Figma-Design</h2>
              <p className="py-2">
                Food-Order-App är en enkel beställnings app. Den byggdes av
                React, Man kan beställa food, add item, remove item osv
              </p>
              <button className="bg-gradient-to-r from-cyan-500 to-blue-500  px-4 py-2 my-3 border-none rounded-md ">
                VIEW CODE
              </button>
            </div>
          </div>
        </section>
        <section>
          <h1 className="text-6xl text-gray-500 p-20 text-center">Skills</h1>
          <div className=" sm:flex flex-wrap justify-center lg:grid grid-cols-4 gap-12 place-items-center text-center text-white dark:text-gray-800">
            <div className="flex flex-col items-center">
              <Image src={html} alt="html" />
              <p>HTML</p>
            </div>
            <div className="flex flex-col items-center">
              <Image src={css} alt="html" className="pb-2" />
              <p>CSS</p>
            </div>
            <div className="flex flex-col items-center">
              <Image src={js} alt="html" className="pb-2"/>
              <p>JavaScript</p>
            </div>
            <div className="flex flex-col items-center">
              <Image src={vscode} alt="html" className="pb-2"/>
              <p>VS CODE</p>
            </div>
            <div className="flex flex-col items-center">
              <Image src={materialui} alt="html" className="pb-2"/>
              <p>Material IU</p>
            </div>
            <div className="flex flex-col items-center">
              <Image src={vue} alt="html" className="pb-2"/>
              <p>VUE</p>
            </div>
            <div className="flex flex-col items-center">
              <Image src={react} alt="html" className="pb-2"/>
              <p>React</p>
            </div>
            <div className="flex flex-col items-center">
              <Image src={react} alt="html" className="pb-2"/>
              <p>React Native</p>
            </div>
            <div className="flex flex-col items-center">
              <Image src={expo} alt="html" className="pb-2"/>
              <p>Expo</p>
            </div>
            <div className="flex flex-col items-center">
              <Image src={node} alt="html" className="pb-2"/>
              <p>Node</p>
            </div>
            <div className="flex flex-col items-center">
              <Image src={npm} alt="html" className="pb-2"/>
              <p>NPM</p>
            </div>
            <div className="flex flex-col items-center">
              <Image src={sqlite} alt="html" className="pb-2"/>
              <p>Sqlite</p>
            </div>
            <div className="flex flex-col items-center">
              <Image src={mongodb} alt="html" className="pb-2"/>
              <p>Mongo DB</p>
            </div>
            <div className="flex flex-col items-center">
              <Image src={git} alt="html" className="pb-2"/>
              <p>Git</p>
            </div>
            <div className="flex flex-col items-center">
              <Image src={github} alt="html" className="pb-2"/>
              <p>Github</p>
            </div>
            <div className="flex flex-col items-center">
              <Image src={figmaa} alt="html" className="pb-2"/>
              <p>Figma</p>
            </div>
            <div className="flex flex-col items-center">
              <Image src={access} alt="html" className="pb-2"/>
              <p>Accessibility</p>
            </div>
            <div className="flex flex-col items-center">
              <Image src={responsive} alt="html" className="pb-2"/>
              <p>Responsive Design</p>
            </div>
            {/* <div className="logo">
          <Image src={trello} alt="html" className="pb-2" width='70px' />
          <p>Agil Development </p>
        </div> */}
          </div>
        </section>
        <section className=" dark:text-white">
          <div className="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">
            <h1 className="text-6xl text-cyan-400 dark:text-gray-500 pt-20 text-center">
              Contact
            </h1>
            <div className="text-5xl flex justify-center gap-16 py-20 text-cyan-400 dark:text-gray-600">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
              <AiFillFacebook />
            </div>
            <form action="#" className="space-y-8 ">
              <div>
                <label className="block mb-2 text-sm font-medium text-white dark:text-gray-300">
                  Your email
                </label>
                <input
                  type="email"
                  id="email"
                  className="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-100 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light"
                  placeholder="name@example.com"
                  required
                />
              </div>
              <div className="sm:col-span-2">
                <label className="block mb-2 text-sm font-medium text-white dark:text-gray-400">
                  Your message
                </label>
                <textarea
                  id="message"
                  className="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg shadow-sm border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-100 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"
                  placeholder="Leave a comment..."
                ></textarea>
              </div>
              <button
                type="submit"
                className="bg-gradient-to-r from-cyan-500 to-blue-500  px-4 py-2 my-3 border-none rounded-md"
              >
                Send message
              </button>
            </form>
          </div>
        </section>
      </main>
    </div>
  );
}
